# Generated by Django 2.0.7 on 2018-07-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('register_date', models.CharField(max_length=12)),
                ('aliasName', models.CharField(max_length=15)),
                ('employeeId', models.CharField(max_length=8)),
            ],
        ),
    ]
