# Generated by Django 2.0.7 on 2018-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('index', models.CharField(max_length=5)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
